---
# macOS LaunchAgent for backups
- name: Symlink backup2 plist
  symlink:
    src: "{{ dotfiles_dir }}/backup2/local.strager.back-up.plist"
    dest: "{{ home_dir }}/Library/LaunchAgents/local.strager.back-up.plist"
    force: false
  when: ansible_facts["system"] == "Darwin"
