---
- name: Ensure fish config directory exists
  ansible.builtin.file:
    path: "{{ home_dir }}/.config/fish"
    state: directory
    mode: "0755"

- name: Symlink fish config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/fish/config.fish"
    dest: "{{ home_dir }}/.config/fish/config.fish"
    state: link
    force: false
