---
- name: Symlink zsh directory
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/zsh"
    dest: "{{ home_dir }}/.zsh"
    state: link
    force: false

- name: Symlink zlogin
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/zsh/zlogin"
    dest: "{{ home_dir }}/.zlogin"
    state: link
    force: false

- name: Symlink zprofile
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/zsh/zprofile"
    dest: "{{ home_dir }}/.zprofile"
    state: link
    force: false

- name: Symlink zshrc
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/zsh/zshrc"
    dest: "{{ home_dir }}/.zshrc"
    state: link
    force: false
