---
- name: Symlink gitconfig
  symlink:
    src: "{{ dotfiles_dir }}/git/gitconfig"
    dest: "{{ home_dir }}/.gitconfig"
    force: false

- name: Symlink gitignore
  symlink:
    src: "{{ dotfiles_dir }}/git/gitignore"
    dest: "{{ home_dir }}/.gitignore"
    force: false
