---
- name: Ensure .config directory exists
  ansible.builtin.file:
    path: "{{ home_dir }}/.config"
    state: directory
    mode: "0700"
  when: ansible_facts["system"] == "Linux"

- name: Symlink systemd config
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/systemd"
    dest: "{{ home_dir }}/.config/systemd"
    state: link
    force: false
  when: ansible_facts["system"] == "Linux"
# TODO(strager): daemon-reload

# TODO(strager): sudo cp "$HEREP/root/strager-zfs-unlock.service" /etc/systemd/system/strager-zfs-unlock.service
